articles_per_page: 10
datetime_format: '%Y-%m-%d %H:%M'
externals:
  github: luxrck
home: Sagittarius A*
output: site
summary: "fuck \u2192you \u2191you \u2197you \u2193you \u2199you and \u21A9 you"
theme: default
ga:
  id: UA-99130329-1
